---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  labels:
    app: fluentbit
data:
  fluentbit.conf: |
    [SERVICE]
        flush           1
        log_level       info

    [INPUT]
        name            kubernetes_events
        tag             k8s_events
        kube_url        https://kubernetes.default.svc

    [OUTPUT]
        Name             http
        Match            k8s_events
        host             victorialogs
        port             9428
        uri              /insert/jsonline?_stream_fields=stream&_msg_field=message&_time_field=date
        format           json_lines
        json_date_format iso8601
