apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-config
data:
  default.vcl: |
    vcl 4.0;

    import directors;

    backend server1 {
        .host = "hugo";
        .port = "1313";
    }

    sub vcl_init {
        new websrv = directors.round_robin();
        websrv.add_backend(server1);
    }

    sub vcl_recv {
        # send all traffic to the websrv director:
        unset req.http.cookie;
        set req.url = regsub(req.url, "\?.*", "");
        set req.backend_hint = websrv.backend();
    }
