apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: varnish
  name: varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varnish
  template:
    metadata:
      labels:
        app: varnish
    spec:
      containers:
      - image: atompi/varnish:7.3.0
        name: varnish
        command:
        - "/usr/sbin/varnishd"
        args:
        - "-F"
        - "-a"
        - ":6081"
        - "-f"
        - "/etc/varnish/default.vcl"
        - "-s"
        - "malloc,1G"
        ports:
        - containerPort: 6081
        volumeMounts:
        - name: config
          mountPath: /etc/varnish/default.vcl
          subPath: default.vcl
      volumes:
      - name: config
        configMap:
          name: varnish-config
      nodeSelector:
        node_role: sys-node

---

apiVersion: v1
kind: Service
metadata:
  name: varnish
  labels:
    app: varnish
spec:
  type: ClusterIP
  ports:
  - name: varnish
    port: 6081
    targetPort: 6081
  selector:
    app: varnish
