alertmanager:
  enabled: false

grafana:
  enabled: false

# kubeProxy:
#   enabled: false

# nodeExporter:
#   enabled: false

kube-state-metrics:
  nodeSelector:
    node_role: sys-node
  tolerations:
    - key: CommonAddonsOnly
      operator: "Equal"
      value: "yes"
      effect: "NoSchedule"

prometheusOperator:
  admissionWebhooks:
    deployment:
      nodeSelector:
        node_role: sys-node
      tolerations:
        - key: CommonAddonsOnly
          operator: "Equal"
          value: "yes"
          effect: "NoSchedule"
    patch:
      image:
        tag: v1.4.4
      nodeSelector:
        node_role: sys-node
      tolerations:
        - key: CommonAddonsOnly
          operator: "Equal"
          value: "yes"
          effect: "NoSchedule"
  nodeSelector:
    node_role: sys-node
  tolerations:
    - key: CommonAddonsOnly
      operator: "Equal"
      value: "yes"
      effect: "NoSchedule"

prometheus:
  prometheusSpec:
    enableAdminAPI: true
    enableRemoteWriteReceiver: true
    tolerations:
      - key: CommonAddonsOnly
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
    nodeSelector:
      node_role: sys-node
    retention: 1d
    retentionSize: 4GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "standard"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
      - job_name: "additional-tmp"
        static_configs:
        - targets: ["localhost:9090"]
    remoteWrite:
      - url: http://vminsert:8480/insert/0/prometheus/api/v1/write

# additionalPrometheusRulesMap: {}
